import Head from "next/head";
import Image from "next/image";
import LotteryEntrance from "../components/LotteryEntrance";
import Nav from "../components/Navbar/Nav";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Navbar /> */}
        <Nav />
        <LotteryEntrance />
      </main>
    </div>
  );
}
